---
output:
  html_document:
    keep_md: true
  md_document:
    variant: markdown_github
---

R pkg for <http://www.bloomberg.com/graphics/2015-star-wars-the-force-accounted/>

- `force_character()`:	force/character data
- `force_episode()`:	force/episode data
- `force_type()`:	force/type data
- `good_vs_evil()`:	good vs evil
- `mentions	mentions()`: data
- `strong_with_which_one()`:	strong with which one
- `timeline	timeline data()`:

Go [here](http://rud.is/projects/force_accounted.html) for a much nicer version of the stuff below.

```{r fig.retina=2}
library(forceaccounted)
```

```{r eval=FALSE, echo=TRUE}
good_vs_evil()
```

<div style="background:black">
```{r fig.retina=2, fig.width=10, echo=FALSE}
good_vs_evil()
```
</div>

```{r eval=FALSE, echo=TRUE}
strong_with_which_one()
```

<div style="background:black">
```{r fig.retina=2, fig.width=10, echo=FALSE}
strong_with_which_one()
```
</div>

```{r echo=TRUE, eval=FALSE}
applied_force()
```

<div style="background:black">
<h1 style="color:white; padding:5px">Applied Force</h1>
```{r fig.retina=2, fig.width=10, fig.height=14, echo=FALSE}
applied_force()
```
</div>

```{r echo=TRUE, eval=FALSE}
be_mentioned()
```

<div style="background:black">
```{r fig.retina=2, fig.width=10, fig.height=10, echo=FALSE}
be_mentioned()
```
</div>

```{r echo=TRUE, eval=FALSE}
ebb_and_flow()
```

<div style="background:black">
```{r fig.retina=2, fig.width=10, fig.height=6, echo=FALSE}
ebb_and_flow()
```
</div>
